import type { CollectorConfig } from 'src/types';

export const ENERGY_COLLECTORS: CollectorConfig[] = [
  {
    id: 'basicCollectors',
    name: 'Basic Collector',
    description: 'Harvests quantum energy from the void',
    emoji: '⚡',
    baseCost: { quantumEnergy: 10 },
    costMultiplier: 1.15,
    baseProduction: 1,
    clickPower: 1,
  },
  {
    id: 'quantumReactors',
    name: 'Quantum Reactor',
    description: 'Advanced energy generation through quantum fusion',
    emoji: '🔬',
    baseCost: { quantumEnergy: 50, quantumCrystals: 5 },
    costMultiplier: 1.2,
    baseProduction: 5,
    clickPower: 2,
  },
  {
    id: 'stellarForges',
    name: 'Stellar Forge',
    description: 'Creates energy by forging new stars',
    emoji: '⭐',
    baseCost: { quantumEnergy: 500, quantumCrystals: 25 },
    costMultiplier: 1.25,
    baseProduction: 50,
    clickPower: 5,
  },
  {
    id: 'voidExtractors',
    name: 'Void Extractor',
    description: 'Extracts pure energy from the fabric of space-time',
    emoji: '🌀',
    baseCost: { quantumEnergy: 2500, quantumCrystals: 125 },
    costMultiplier: 1.3,
    baseProduction: 500,
    clickPower: 10,
  },
];

export const CRYSTAL_COLLECTORS: CollectorConfig[] = [
  {
    id: 'basicMines',
    name: 'Basic Mine',
    description: 'Extracts quantum crystals from dimensional pockets',
    emoji: '💎',
    baseCost: { quantumEnergy: 25 },
    costMultiplier: 1.15,
    baseProduction: 1,
    clickPower: 1,
  },
  {
    id: 'quantumDrills',
    name: 'Quantum Drill',
    description: 'Advanced crystal extraction through quantum tunneling',
    emoji: '🔧',
    baseCost: { quantumEnergy: 125, quantumCrystals: 10 },
    costMultiplier: 1.2,
    baseProduction: 5,
    clickPower: 2,
  },
  {
    id: 'stellarExtractors',
    name: 'Stellar Extractor',
    description: 'Harvests crystals from stellar cores',
    emoji: '🌟',
    baseCost: { quantumEnergy: 1250, quantumCrystals: 50 },
    costMultiplier: 1.25,
    baseProduction: 50,
    clickPower: 5,
  },
  {
    id: 'voidHarvesters',
    name: 'Void Harvester',
    description: 'Pulls crystals from the void between dimensions',
    emoji: '💫',
    baseCost: { quantumEnergy: 6250, quantumCrystals: 250 },
    costMultiplier: 1.3,
    baseProduction: 500,
    clickPower: 10,
  },
];
