import type { CollectorConfig } from 'src/types';

export const ENERGY_COLLECTORS: CollectorConfig[] = [
  {
    id: 'basicCollectors',
    name: 'Basic Collector',
    description: 'Harvests quantum energy from the void',
    emoji: '⚡',
    baseCost: { quantumEnergy: 15 },
    costMultiplier: 1.15,
    baseProduction: 1,
    clickPower: 0,
  },
  {
    id: 'quantumReactors',
    name: 'Quantum Reactor',
    description: 'Advanced energy generation through quantum fusion',
    emoji: '🔬',
    baseCost: { quantumEnergy: 100 },
    costMultiplier: 1.2,
    baseProduction: 5,
    clickPower: 0,
  },
  {
    id: 'stellarForges',
    name: 'Stellar Forge',
    description: 'Creates energy by forging new stars',
    emoji: '⭐',
    baseCost: { quantumEnergy: 1000, quantumCrystals: 50 },
    costMultiplier: 1.25,
    baseProduction: 50,
    clickPower: 0,
  },
  {
    id: 'voidExtractors',
    name: 'Void Extractor',
    description: 'Extracts pure energy from the fabric of space-time',
    emoji: '🌀',
    baseCost: { quantumEnergy: 10000, quantumCrystals: 500 },
    costMultiplier: 1.3,
    baseProduction: 500,
    clickPower: 0,
  },
  {
    id: 'dimensionalRifts',
    name: 'Dimensional Rift',
    description: 'Taps into parallel dimensions for unlimited energy',
    emoji: '🌌',
    baseCost: { quantumEnergy: 100000, quantumCrystals: 5000 },
    costMultiplier: 1.35,
    baseProduction: 5000,
    clickPower: 0,
  },
  {
    id: 'cosmicGenerators',
    name: 'Cosmic Generator',
    description: 'Harnesses the power of entire galaxies',
    emoji: '🌠',
    baseCost: { quantumEnergy: 1000000, quantumCrystals: 50000 },
    costMultiplier: 1.4,
    baseProduction: 50000,
    clickPower: 0,
  },
];

export const CRYSTAL_COLLECTORS: CollectorConfig[] = [
  {
    id: 'basicMines',
    name: 'Basic Mine',
    description: 'Extracts quantum crystals from dimensional pockets',
    emoji: '💎',
    baseCost: { quantumEnergy: 30 },
    costMultiplier: 1.15,
    baseProduction: 1,
    clickPower: 0,
  },
  {
    id: 'quantumDrills',
    name: 'Quantum Drill',
    description: 'Advanced crystal extraction through quantum tunneling',
    emoji: '🔧',
    baseCost: { quantumEnergy: 200, quantumCrystals: 20 },
    costMultiplier: 1.2,
    baseProduction: 5,
    clickPower: 0,
  },
  {
    id: 'stellarExtractors',
    name: 'Stellar Extractor',
    description: 'Harvests crystals from stellar cores',
    emoji: '🌟',
    baseCost: { quantumEnergy: 2000, quantumCrystals: 100 },
    costMultiplier: 1.25,
    baseProduction: 50,
    clickPower: 0,
  },
  {
    id: 'voidHarvesters',
    name: 'Void Harvester',
    description: 'Pulls crystals from the void between dimensions',
    emoji: '💫',
    baseCost: { quantumEnergy: 20000, quantumCrystals: 1000 },
    costMultiplier: 1.3,
    baseProduction: 500,
    clickPower: 0,
  },
  {
    id: 'dimensionalMines',
    name: 'Dimensional Mine',
    description: 'Mines crystals from alternate realities',
    emoji: '🔮',
    baseCost: { quantumEnergy: 200000, quantumCrystals: 10000 },
    costMultiplier: 1.35,
    baseProduction: 5000,
    clickPower: 0,
  },
  {
    id: 'cosmicRefineries',
    name: 'Cosmic Refinery',
    description: 'Refines raw cosmic matter into pure crystals',
    emoji: '✨',
    baseCost: { quantumEnergy: 2000000, quantumCrystals: 100000 },
    costMultiplier: 1.4,
    baseProduction: 50000,
    clickPower: 0,
  },
];
